"""correct fk type (int)

Revision ID: 55e7b92fa3ea
Revises: 8dbac9b43d88
Create Date: 2025-11-09 18:21:57.071803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e7b92fa3ea'
down_revision: Union[str, Sequence[str], None] = '8dbac9b43d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
