"""add search vector for products

Revision ID: a32da0ca5925
Revises: 55e7b92fa3ea
Create Date: 2025-11-13 21:43:55.006720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a32da0ca5925'
down_revision: Union[str, Sequence[str], None] = '55e7b92fa3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'products',
        sa.Column(
            'tsv',
            postgresql.TSVECTOR(),
            sa.Computed(
                """
                setweight(to_tsvector('english', coalesce(name, '')), 'A')
                ||
                setweight(to_tsvector('english', coalesce(description, '')), 'B')
                """,
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index('ix_products_tsv_gin', 'products', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_tsv_gin', table_name='products', postgresql_using='gin')
    op.drop_column('products', 'tsv')
    # ### end Alembic commands ###
